// <auto-generated />
namespace EExam.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class chaptersaddedfacultylevelatrraddeddifflevelforquestionsadded_ : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(chaptersaddedfacultylevelatrraddeddifflevelforquestionsadded_));
        
        string IMigrationMetadata.Id
        {
            get { return "202003111154016_chapters added , faculty level atrr added , diff level for questions added  _"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
