// <auto-generated />
namespace EExam.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class questiondifflevelbecameint : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(questiondifflevelbecameint));
        
        string IMigrationMetadata.Id
        {
            get { return "202003111157258_question diff level became int "; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
